config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
      :sessions => 'admins/sessions'
  }

  devise_scope :admin do
    root to: 'admins/sessions#new'
  end

  resources :employees, :only => [:index, :new, :create]
  
end

app/models/employee.rb
require 'csv'
class Employee < ApplicationRecord

  validates :first_name, :last_name, :annual_salary, :super_rate, :pay_period, presence: true
  validates :annual_salary, numericality: { only_integer: true, greater_than: 0 }

  before_create :calculation_rate

  def name
    "#{first_name} #{last_name}"
  end

  def rate_level
    tax = case annual_salary
          when 0..18200
            0
          when 18201..37000
            (0.19 * (annual_salary - 18200))
          when 37001..80000
            (3572 + (annual_salary - 37000) * 0.325)
          when 80001..180000
            (17547 + (annual_salary - 80000) * 0.37)
          when 180001..Float::INFINITY
            (54547 + (annual_salary - 180000) * 0.45)
          end
    tax.zero? ? 0 : (tax / 12).round
  end


  private
  def calculation_rate
    if annual_salary.present?
      self.gross_income = (annual_salary / 12).round
      self.income_tax = rate_level
      self.net_income = gross_income - income_tax
      self.super_res = (gross_income * super_rate).round
    end
  end

  class << self

    def import(file)
      raise "请选择csv文件上传!" unless file.is_a?(ActionDispatch::Http::UploadedFile)
      CSV.foreach(file.tempfile) do |row|
        data = {
            first_name: row[0].strip,
            last_name: row[1].strip,
            annual_salary: row[2].strip,
            super_rate: row[3],
            pay_period: row[4]
        }
        employee = Employee.find_or_initialize_by(first_name: data[:first_name], last_name: data[:last_name])
        employee.update_attributes!(data)
      end
    end
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @pay_periods = Employee.select(:pay_period).distinct
    if params[:pay_period].present?
      @employees = Employee.where(pay_period: params[:pay_period])
    else
      @employees = Employee.all
    end
  end

  def new
    @employee = Employee.new
  end


  def create
    begin
      @file = params.require(:employee)[:file]
      Employee.import(@file)
      redirect_to employees_path
    rescue Exception => exception
      @employee = Employee.new
      flash[:error] = "导入失败! #{ exception.message }"
      render action: :new, formats: [:html]
    end
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/index.html.erb
<!-- START PANEL -->
<div style="width: 100%; height: 55px; background-color: #dedddd">

  <%=form_tag employees_path, method: :get do |f| %>
      <span style="font-size: 20px;">Search Condition: </span>
      <%= select_tag('pay_period', options_from_collection_for_select(@pay_periods, "id", "pay_period", params[:pay_period])) %>
      <%=submit_tag 'search', class: "btn btn-default search-btn"  %>
  <% end %>
  <%= link_to "IMPORT CSV", new_employee_path, class: "btn btn-warning import-btn pull-right" %>
  <!--<button class="btn btn-warning import-btn pull-right" data-toggle="modal" data-target="#page-dialog">IMPORT CSV</button>-->
</div>

<hr style="margin: 10px"/>

<table class="table">
  <thead>
    <tr>
      <th class="col-lg-2 col-md-2 col-sm-2 name">name</th>
      <th class="col-lg-2 col-md-2 col-sm-2">pay period</th>
      <th class="col-lg-2 col-md-2 col-sm-2">gross income</th>
      <th class="col-lg-2 col-md-2 col-sm-2">income tax</th>
      <th class="col-lg-2 col-md-2 col-sm-2">net income</th>
      <th class="col-lg-2 col-md-2 col-sm-2">super</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
        <tr>
          <td class="col-lg-2 col-md-2 col-sm-2 name"><%= employee.name %></td>
          <td class="col-lg-2 col-md-2 col-sm-2"><%= employee.pay_period %></td>
          <td class="col-lg-2 col-md-2 col-sm-2"><strong>$</strong> <%= employee.gross_income %></td>
          <td class="col-lg-2 col-md-2 col-sm-2"><strong>$</strong> <%= employee.income_tax %></td>
          <td class="col-lg-2 col-md-2 col-sm-2"><strong>$</strong> <%= employee.net_income %></td>
          <td class="col-lg-2 col-md-2 col-sm-2"><strong>$</strong> <%= employee.super_res %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<!-- END PANEL -->

app/views/employees/new.html.erb
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>
<%= form_for(@employee, :multipart => true, class: "import") do |f| %>
    <%= f.file_field :file, accept: '.csv', class: "btn btn-default" %>
    <%= f.submit :submit, class: "btn btn-default" %>
<% end %>