config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
      :sessions => 'admins/sessions'
  }

  devise_scope :admin do
    root to: 'admins/sessions#new'
  end

  resources :employees, :only => [:index, :new, :create]
  
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer">
    <span>Copyright &copy; 2017 Keon Ye. All Rights Reserved.</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--<header>-->
  <!--<div class="header">-->
    <!--<div class="head-title">-->
      <!--&lt;!&ndash;<img src="/images/logo.jpg" width="28px" height="28px" style="display: inline"/>&ndash;&gt;-->
      <!--<span style="display: inline">Employee Payslip Management System</span>-->
    <!--</div>-->
  <!--</div>-->
<!--</header>-->


<!-- BEGIN TOPBAR -->
<div class="topbar">
  <div class="header-right">
    <ul class="header-menu nav navbar-nav">
      <!-- BEGIN USER DROPDOWN -->
      <li class="text-center" id="date" style="margin: 10px"></li>
      <li class="text-center" id="time" style="margin-top: 10px"></li>
      <!-- END USER DROPDOWN -->
    </ul>
  </div>
  <!-- header-right -->
</div>
<!-- END TOPBAR -->

<script type="text/javascript" language="javascript">
  Date.prototype.Format = function (fmt) { //author: meizz
    var o = {
      "M+": this.getMonth() + 1, //月份
      "d+": this.getDate(), //日
      "h+": this.getHours(), //小时
      "m+": this.getMinutes(), //分
      "s+": this.getSeconds(), //秒
      "q+": Math.floor((this.getMonth() + 3) / 3), //季度
      "S": this.getMilliseconds() //毫秒
    };
    if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
    for (var k in o)
      if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
    return fmt;
  }

  function setTime() {
    var currentTime = new Date();
    document.getElementById("time").innerHTML = currentTime.Format("hh:mm:ss");
    document.getElementById("date").innerHTML = currentTime.Format("yyyy/MM/dd");
  }
  setInterval(setTime, 1000);
</script>

app/views/layouts/_side_bar.html.erb
<!-- BEGIN SIDEBAR -->
<div class="sidebar">
  <div class="logo-panel">
    <a href="/home/console">
      <%= image_tag "/images/logo.jpg", height: 20 %>
      &nbsp;&nbsp;
      <span style="font-size: 20px; vertical-align: middle; letter-spacing: 0px; color: #fff;">
        EPM SYSTEM
      </span>
    </a>
  </div>
  <hr style="margin: -2px 0px 4px;">
  <div class="sidebar-inner">
    <%= image_tag "/images/admin.png", height: 80 , style: 'border-radius: 50%; margin: 4px 50px;' %>
    <div style="display: block;">
      <h4 style="color: #fff; text-align: center"><%= current_admin.email %></h4>
    </div>

    <div class="nav-menu">
      <ul class="nav nav-sider">
        <li>
          <a href=<%= employees_path %> onclik style="padding-bottom: 2px">
            <i style="margin: 5px 10px 0 0" class="icon icon-credit-card"></i>
            <span style="">payslip management</span>
          </a>
        </li>
      </ul>
    </div>

    <div class="sidebar-footer">
      <a class="pull-left" href="#" data-rel="tooltip" data-placement="top" data-original-title="设置">
        <i class="icon-settings"></i></a>
      <a class="pull-left" href="#" data-rel="tooltip" data-placement="top" data-original-title="全屏显示">
        <i class="icon-size-fullscreen"></i></a>
      <a class="pull-left" href="<%= destroy_admin_session_path %>" data-rel="tooltip" data-placement="top" data-original-title="锁屏">
        <i class="icon-lock"></i></a>
    </div>
  </div>
</div>
<!-- END SIDEBAR -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payslip</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/images/favicon.ico">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag '/fonts/line-icons/simple-line-icons' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag "/themes/default/custom.css", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "/themes/default/custom.js" %>

  </head>

  <body>

    <!--[if lt IE 7]>
    <p class="browsehappy">您的浏览器<strong>版本过低</strong>. 请<a href="http://browsehappy.com/">更新您的浏览器</a>.</p>
    <![endif]-->

    <%= render partial: 'layouts/side_bar' %>

    <div class="main-content" style="min-width: 1150px">
      <%= render partial: 'layouts/header' %>
      <div class="page-content page-thin">
        <!-- START CONTAINER FLUID -->
        <div class="container-fluid">
          <!-- BEGIN PAGE CONTENT -->
          <%= yield %>
          <!-- END PAGE CONTENT -->
        </div>
      </div>
    </div>

    <!-- footer -->
    <%= render partial: 'layouts/footer' %>

    <!-- Common Modal -->
    <div id="confirm-dialog" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close"
                    data-dismiss="modal" aria-hidden="true">
              &times;
            </button>
            <h4 class="modal-title"></h4>
          </div>
          <div class="modal-body clearfix">
            <!-- content here -->
          </div>
          <div class="modal-footer">
            <a class="btn btn-default" data-dismiss="modal">Close</a>
            <a class="btn btn-primary btn-confirm-ok cola-green-bg">Save</a>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal -->
    </div>

    <!-- Page Modal -->
    <div id="page-dialog" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Ttile</h4>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Submit</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal -->
    </div>

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Payslip</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/images/favicon.ico">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css">

      body {
        background: url("/images/login-bg.jpg");
        background-size: 1000px 1000px;
      }

      .account-wall {
        margin-top: 80px;
        padding: 20px 20px 10px;
        position: relative;
      }
      .form-control.form-white {
        border: 1px solid #bbbbbb;
      }

      .append-icon {
        position: relative;
      }

      .m-b-10 {
        margin-bottom: 10px !important;
      }

      .m-b-20 {
        margin-bottom: 20px !important;
      }

      .append-icon input {
        padding-right: 36px;
      }

      .append-icon i {
        color: rgba(27,30,37,0.3);
        font-size: 14px;
        height: 34px;
        left: auto;
        line-height: 34px;
        position: absolute;
        right: 0;
        text-align: center;
        top: 0;
        width: 36px;
      }

      .account .btn {
        font-size: 15px;
        padding: 6px 48px 6px;
      }

      .ladda-button {
        position: relative;
      }

      .c-white {
        color: #fff;
      }

      .theme-green-bg {
        background: #7AB800 !important;
      }

      #logo img {
        height: 120px;
        margin-right: 40px;
        margin-bottom: 20px;
      }

      footer {
        background-color: transparent;
      }

      footer span {
        color: #0a0a0a;
      }

    </style>
  </head>

  <body >

    <!--[if lt IE 7]>
    <p class="browsehappy">您的浏览器<strong>版本过低</strong>. 请<a href="http://browsehappy.com/">更新您的浏览器</a>.</p>
    <![endif]-->

    <!-- BEGIN LOGIN BOX -->
    <div class="container" id="login-block">
      <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
          <div class="account-wall">
            <div id="logo" class="text-center cola-gray-4" style="font-size: 15px;">
              <img style="" src="/images/logo.jpg" alt="Logo" />
            </div>

            <% if flash[:error] %>
                <div class="alert alert-danger fade in">
                  <%= flash[:error] %>
                </div>
            <% end %>

            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="append-icon m-b-10">
                  <!--input type="email" name="admin[email]" id="username" class="form-control form-white username" placeholder="Email" required-->
                  <%= f.text_field :email, :type => 'email', :class => 'form-control form-white username', :placeholder => 'Email', :required => true %>
                  <i class="icon-user"></i>
                </div>
                <div class="append-icon m-b-20">
                  <input type="password" name="admin[password]" class="form-control form-white password" placeholder="密码" required>
                  <i class="icon-lock"></i>
                </div>

                <button type="submit" class="btn btn-lg btn-block ladda-button theme-green-bg c-white" data-style="expand-left">登 录
                </button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <!-- END LOGIN BOX -->

    <!-- footer -->
    <%= render partial: 'layouts/footer' %>

  </body>
</html>